---
- name: SHOW WAN INTERFACE ERRORS
  hosts: 'hubs,spokes'
  gather_facts: false
  connection: local

  tasks:
    - name: SHOW INT ERRORS
      ios_command:
        commands:
          - show int {{ wan_int }} | i errors
      register: print_output
    - debug: var=print_output.stdout_lines
