---
- name: SHOW WAN INTERFACE SPEED AND DUPLEX
  hosts: 'hubs,spokes'
  gather_facts: false
  connection: local

  tasks:
    - name: SHOW INT SPEED + DUPLEX
      ios_command:
        commands:
          - show int {{ wan_int }} | i Duplex
      register: print_output
    - debug: var=print_output.stdout_lines
