---
- name: SHOW ROUTING NEIGHBOURS
  hosts: 'hubs,spokes'
  gather_facts: false
  connection: local

  tasks:
    - name: SHOW IP EIGRP NEIGHBOURS
      ios_command:
        timeout: 30
        authorize: yes
        commands:
          - show ip eigrp nei
      register: print_output
    - debug: var=print_output.stdout_lines
