---
- name: SHOW IP NAT TRANSLATIONSS
  hosts: 'hubs,spokes'
  gather_facts: false
  connection: local

  tasks:
    - name: SHOW IP NAT TRANSLATIONS 
      ios_command:
        commands:
          - show ip nat translations
      register: print_output
    - debug: var=print_output.stdout_lines
