---
- name: VERIFY DMVPN ON A ROUTER
  hosts: '{{ target }}'
  gather_facts: false
  connection: local

  vars:
    cli:
      username: "{{ username}}"
      password: "{{ password }}"

  tasks:

    - name: CHECK TUNNEL INT | EIGRP | NHRP | DMVPN
      ios_command:
        provider: "{{ cli }}"
        timeout: 30
        commands:
          - sh ip int br | i Tunnel
          - sh ip eigrp nei
          - sh ip route summary
          - sh ip nhrp static
          - sh dmvpn static | begin Interface
      register: print_output

    - debug: var=print_output.stdout_lines
