##########################################
#used to verify the OSPF routing protocol#
##########################################

---
- name: VERIFY OSPF ROUTING PROTOCOL
  hosts: 'routers'
  gather_facts: false
  connection: local

  tasks:

    - name: CHECK PROCESS | DATABASE | INTERFACES | NEIGHBOURS 
      ios_command:
        timeout: 30
        commands:
          - sh ip ospf 
          - show ip ospf database 
          - show ip ospf interface
          - show ip ospf neighbor
      register: print_output
    - debug: var=print_output.stdout_lines
